# Generated by Django 4.0.3 on 2023-03-19 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='image',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
